#!/usr/bin/env bash
# =============================================================================
# import-validators-grandine.sh
# Imports all Ethereum validator keystores into Grandine,
# automatically reading the password from the matching .txt file.
#
# Each keystore-N.json has a matching keystore-N.txt with its own password,
# as generated by the Obol cluster creation process.
#
# Grandine has no import command — it reads keystores directly from
# --keystore-dir at startup. This script copies each keystore to the
# Grandine keystore directory and writes a matching password file in
# --keystore-password-dir (one file per keystore, named by pubkey).
#
# Usage:
#   chmod +x import-validators-grandine.sh
#   ./import-validators-grandine.sh
#
# Requirements:
#   - python3 (for pubkey extraction from keystore JSON)
# =============================================================================

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
KEYS_DIR="/home/ethereum/.charon/validator_keys"
GRANDINE_KEYSTORE_DIR="/home/ethereum/.grandine/mainnet/validators"
GRANDINE_PASSWORD_DIR="/home/ethereum/.grandine/mainnet/validator_passwords"
# ─────────────────────────────────────────────────────────────────────────────

if ! command -v python3 &>/dev/null; then
  echo "[ERROR] 'python3' is not installed."
  exit 1
fi

mapfile -t KEYSTORES < <(find "$KEYS_DIR" -maxdepth 1 -name "keystore-*.json" | sort)

if [[ ${#KEYSTORES[@]} -eq 0 ]]; then
  echo "[ERROR] No keystore-*.json files found in: $KEYS_DIR"
  exit 1
fi

echo "══════════════════════════════════════════════════════"
echo "  Grandine Validator Import"
echo "  Keys directory    : $KEYS_DIR"
echo "  Keystore dir      : $GRANDINE_KEYSTORE_DIR"
echo "  Password dir      : $GRANDINE_PASSWORD_DIR"
echo "  Keystores found   : ${#KEYSTORES[@]}"
echo "══════════════════════════════════════════════════════"
echo ""
echo "  ℹ️  Grandine reads keystores from --keystore-dir at startup."
echo "     Ensure your service has:"
echo "     --keystore-dir $GRANDINE_KEYSTORE_DIR"
echo "     --keystore-password-dir $GRANDINE_PASSWORD_DIR"
echo ""

# Create directories
mkdir -p "$GRANDINE_KEYSTORE_DIR" "$GRANDINE_PASSWORD_DIR"
chmod 700 "$GRANDINE_KEYSTORE_DIR" "$GRANDINE_PASSWORD_DIR"

SUCCESS=0
FAILED=0
SKIPPED=0

for KEYSTORE_PATH in "${KEYSTORES[@]}"; do
  KEYSTORE_FILE=$(basename "$KEYSTORE_PATH")
  BASE="${KEYSTORE_FILE%.json}"
  PASSWORD_FILE="$KEYS_DIR/${BASE}.txt"

  echo "──────────────────────────────────────────────────────"
  echo "  Keystore : $KEYSTORE_FILE"

  if [[ ! -f "$PASSWORD_FILE" ]]; then
    echo "  [SKIP] No matching password file: ${BASE}.txt"
    (( SKIPPED++ )) || true
    continue
  fi

  PASSWORD=$(< "$PASSWORD_FILE")

  if [[ -z "$PASSWORD" ]]; then
    echo "  [SKIP] Password file is empty: ${BASE}.txt"
    (( SKIPPED++ )) || true
    continue
  fi

  # Extract pubkey from keystore JSON (used as password filename for Grandine)
  PUBKEY=$(python3 -c "
import json, sys
try:
    data = json.load(open('$KEYSTORE_PATH'))
    pubkey = data.get('pubkey', '')
    # Remove 0x prefix if present
    print(pubkey.lstrip('0x'))
except Exception as e:
    print('', end='')
" 2>/dev/null)

  if [[ -z "$PUBKEY" ]]; then
    echo "  [FAIL] Could not extract pubkey from $KEYSTORE_FILE"
    (( FAILED++ )) || true
    continue
  fi

  DEST_KEYSTORE="$GRANDINE_KEYSTORE_DIR/$KEYSTORE_FILE"
  DEST_PASSWORD="$GRANDINE_PASSWORD_DIR/0x${PUBKEY}.txt"

  echo "  Pubkey   : 0x${PUBKEY:0:12}…"
  echo "  Password : loaded from ${BASE}.txt"

  # Copy keystore (skip if already present)
  if [[ -f "$DEST_KEYSTORE" ]]; then
    echo "  [SKIP] Keystore already present in $GRANDINE_KEYSTORE_DIR"
    (( SKIPPED++ )) || true
    continue
  fi

  cp "$KEYSTORE_PATH" "$DEST_KEYSTORE"
  chmod 600 "$DEST_KEYSTORE"

  # Write per-keystore password file named by pubkey
  echo "$PASSWORD" > "$DEST_PASSWORD"
  chmod 600 "$DEST_PASSWORD"

  echo "  [OK] Copied keystore and password"
  (( SUCCESS++ )) || true

done

echo ""
echo "══════════════════════════════════════════════════════"
echo "  Import Summary"
echo "  ✔ Success : $SUCCESS"
echo "  ✗ Failed  : $FAILED"
echo "  ⊘ Skipped : $SKIPPED"
echo "══════════════════════════════════════════════════════"

[[ $FAILED -gt 0 ]] && exit 1
exit 0
