#!/bin/sh
# postinst script for dvt-obol

# Exit immediately if a command fails.
set -e

case "$1" in
    configure | "")
        # Set the correct ownership and permissions for the
        # cron.d file.
        #
        # This is a security requirement for cron.
        # If the file doesn't exist, 'set -e' will cause the script
        # to fail, notifying the user of the installation error.

        chown root:root /etc/cron.d/sync_charon_config
        chmod 644 /etc/cron.d/sync_charon_config
    ;;

    abort-upgrade | abort-remove | abort-deconfigure)
        # No action required on these cases.
    ;;

    *)
        echo "postinst for dvt-obol called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0