name: Bug report
description: Create a report to help us improve Ethereum on ARM
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: I am experiencing...
    validations:
      required: true
  - type: input
    id: board
    attributes:
      label: Board
      description: e.g. Raspberry Pi 4, Rock 5B
      placeholder: Raspberry Pi 4
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS Image
      description: e.g. Ubuntu 24.04, Armbian
      placeholder: Ubuntu 24.04
    validations:
      required: true
  - type: dropdown
    id: install_method
    attributes:
      label: Installation method
      options:
        - Image
        - Package
        - Manual Source Build
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: logs
    attributes:
      label: Screenshots/Logs
      description: If applicable, add screenshots or logs to help explain your problem.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
