{
 "title": "Ethrex",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "network",
    "query": {
     "query": "label_values(eth_con_spec_config_name,name)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(eth_con_spec_config_name{name=~\"$network\"},instance)"
    }
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "job", "label": "job", "query": { "query": "label_values(up, job)" } }
  ]
 },
 "panels": [
  {
   "title": "Execution Client",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (instance, client, version)(eth_exe_web3_client_version{instance=~\"$instance(:\\\\d+)?$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Config",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "eth_con_spec_config_name{instance=~\"$instance(:\\\\d+)?$\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Consensus Fork",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "eth_con_fork_current{instance=~\"$instance(:\\\\d+)?$\"}",
     "legendFormat": "{{fork}}"
    }
   ]
  },
  { "title": "Block Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Gas Used %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance)(\n  gas_used{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"}\n)\n/\non(instance)\n  sum by (instance)(\n    gas_limit{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"} \n  )",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Ggas/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Ggas/s" } },
   "targets": [
    {
     "expr": "gigagas{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"} - 0",
     "legendFormat": "{{ instance }} Gigagas/s"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 6 },
   "targets": [
    {
     "expr": "head_height{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"}",
     "legendFormat": "{{ instance }} Head height"
    }
   ]
  },
  {
   "title": "Ggas/s by Block",
   "type": "xychart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "gigagas{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"}",
     "legendFormat": "ggas/s {{ instance }}"
    },
    {
     "expr": "max without(instance) (last_over_time(block_number{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"}[$__rate_interval]))",
     "legendFormat": "Block"
    },
    {
     "expr": "scalar(\n  max(\n    ( max without(instance) (\n        last_over_time(block_number{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"}[$__rate_interval])\n      )\n      == bool\n      min without(instance) (\n        last_over_time(block_number{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"}[$__rate_interval])\n      )\n  ))\n)",
     "legendFormat": "all_same_block"
    }
   ]
  },
  {
   "title": "Block Time",
   "type": "xychart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (instance)(\n  gas_used{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"}\n)\n/\non(instance) ( \n  sum by (instance)(\n    gigagas{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"} \n  ) * 1000000000\n)",
     "legendFormat": "Block time {{ instance }}"
    },
    {
     "expr": "max without(instance) (last_over_time(block_number{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"}[$__rate_interval]))",
     "legendFormat": "Block"
    },
    {
     "expr": "scalar(\n  max(\n    ( max without(instance) (\n        last_over_time(block_number{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"}[$__rate_interval])\n      )\n      == bool\n      min without(instance) (\n        last_over_time(block_number{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"}[$__rate_interval])\n      )\n  ))\n)",
     "legendFormat": "all_same_block"
    }
   ]
  },
  { "title": "Block Execution Breakdown ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Block Execution Breakdown - $instance",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 27 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (function_name) (\n    increase(function_duration_seconds_sum{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\", namespace!~\"rpc|engine\", function_name!~\"Block execution|Execute Block|Trie update\"}[$__range])\n  )\n)\nor\nlabel_replace(\n  sum( increase(function_duration_seconds_sum{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\", namespace!~\"rpc|engine\", function_name=\"Block execution\"}[$__range]) )\n  - sum( increase(function_duration_seconds_sum{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\", namespace!~\"rpc|engine\", function_name=~\"Storage read|Account read|Account code read|Block hash read\"}[$__range]) ),\n  \"function_name\",\"Block Execution (w/o reads)\",\"__name__\",\".*\"\n)\nor\nlabel_replace(\n  sum( increase(function_duration_seconds_sum{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\", namespace!~\"rpc|engine\", function_name=\"Execute Block\"}[$__range]) )\n  - sum( increase(function_duration_seconds_sum{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\", namespace!~\"rpc|engine\", function_name=\"Block execution\"}[$__range]) ),\n  \"function_name\",\"Merkleization Diff\",\"__name__\",\".*\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution vs Merkleization Diff % - $instance",
   "type": "timeseries",
   "description": "This panel shows the difference between the Execution vs merkleization in the `execute_block_pipeline` function. It's shown as a percentage of the whole function. If it's negative, execution took more time than merkleization.",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 27 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "label_replace(\n  (sum( increase(function_duration_seconds_sum{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\", namespace!~\"rpc|engine\", function_name=\"Trie update\"}[$__range]) )\n  - sum( increase(function_duration_seconds_sum{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\", namespace!~\"rpc|engine\", function_name=\"Block execution\"}[$__range]) ))\n  / sum( increase(function_duration_seconds_sum{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\", namespace!~\"rpc|engine\", function_name=\"Execute Block\"}[$__range]) ),\n  \"function_name\",\"Execution vs Merkleization Diff %\",\"__name__\",\".*\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Execution Deaggregated by Block - $instance",
   "type": "xychart",
   "description": "This Panel shows the deaggregated measures of the current instrumentation we have for block processing tied by block.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 27 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(\n  # Calculates the Execute Block first and removes zeroes generated by idelta to smooth the panel\n  sum by (instance, function_name) (\n    clamp_min(\n      idelta(function_duration_seconds_sum{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\", namespace!~\"rpc|engine\", function_name=\"Execute Block\"}[$__rate_interval]),\n      0\n    )\n  )\n) > 0\nor\n(\n# Calculates the rest of the instruments, except Execute Block, which was calculated before\n  sum by (instance, function_name) (\n    clamp_min(\n      idelta(function_duration_seconds_sum{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\", namespace!~\"rpc|engine\", function_name!~\"Execute Block|Block execution\"}[$__rate_interval]),\n      0\n    )\n  )\n)\nor\nlabel_replace(\n  sum by (instance) (\n    clamp_min(\n      idelta(function_duration_seconds_sum{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\", namespace!~\"rpc|engine\", function_name=\"Block execution\"}[$__rate_interval]),\n      0\n    )\n  )\n  - sum by (instance) (\n    clamp_min(\n      idelta(function_duration_seconds_sum{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\", namespace!~\"rpc|engine\", function_name=~\"Storage read|Account read|Account code read|Block hash read\"}[$__rate_interval]),\n      0\n    )\n  ),\n  \"function_name\",\"Block Execution (w/o reads)\",\"instance\",\".*\"\n)",
     "legendFormat": "{{instance}} {{function_name}}"
    },
    {
     "expr": "max without(instance) (last_over_time(block_number{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"}[$__rate_interval]))",
     "legendFormat": "Block"
    },
    {
     "expr": "scalar(\n  max(\n    ( max without(instance) (\n        last_over_time(block_number{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"}[$__rate_interval])\n      )\n      == bool\n      min without(instance) (\n        last_over_time(block_number{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"}[$__rate_interval])\n      )\n  ))\n)",
     "legendFormat": "all_same_block"
    }
   ]
  },
  { "title": "Engine API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Engine Request Rate by Method - $instance",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 41 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (function_name) (\n  rate(function_duration_seconds_count{\n    job=\"$job\",\n    instance=~\"$instance(:\\\\d+)?$\",\n    namespace=\"engine\"\n  }[$__range])\n)",
     "legendFormat": "{{function_name}}"
    }
   ]
  },
  {
   "title": "Engine Latency by Methods (AVG Duration) - $instance",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 5, "x": 7, "y": 41 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (function_name) (increase(function_duration_seconds_sum{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\", namespace=\"engine\"}[$__range])) \n/ sum by (function_name) (increase(function_duration_seconds_count{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\", namespace=\"engine\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Engine Latency by Method - $instance",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 41 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (function_name) (increase(function_duration_seconds_sum{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\", namespace=\"engine\"}[18s])) \n/ sum by (function_name) (increase(function_duration_seconds_count{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\", namespace=\"engine\"}[18s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RPC API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "RPC Average Time per Method - $instance",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 56 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (function_name) (increase(function_duration_seconds_sum{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\", namespace=\"rpc\"}[$__range]))",
     "legendFormat": "{{function_name}}"
    }
   ]
  },
  {
   "title": "Slowest RPC Methods (Avg Duration) - $instance",
   "type": "table",
   "gridPos": { "h": 14, "w": 5, "x": 7, "y": 56 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(function_duration_seconds_sum{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\", namespace=\"rpc\"}[$__range]) / rate(function_duration_seconds_count{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\", namespace=\"rpc\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC Request Rate by Method - $instance",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 56 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (function_name) (rate(function_duration_seconds_count{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\", namespace=\"rpc\"}[$__range]))",
     "legendFormat": "{{function_name}}"
    }
   ]
  },
  {
   "title": "RPC Latency by Methods - $instance",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 56 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (function_name) (increase(function_duration_seconds_sum{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\", namespace=\"rpc\"}[18s])) \n/ sum by (function_name) (increase(function_duration_seconds_count{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\", namespace=\"rpc\"}[18s]))",
     "legendFormat": "{{ function_name }}"
    }
   ]
  },
  { "title": "Process & Server Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"}",
     "legendFormat": "uptime_s"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_threads{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"}",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "Open FDs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"}",
     "legendFormat": "Open FDs"
    }
   ]
  },
  {
   "title": "Datadir Size",
   "type": "timeseries",
   "description": "This calculates the size in bytes of the datadir path where the DB is stored.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "datadir_size_bytes{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"}",
     "legendFormat": "{{ instance }} Datadir Size (GB)"
    }
   ]
  },
  {
   "title": "Open FDs Historic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "process_open_fds{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"}",
     "legendFormat": "{{ instance }} FDs used"
    }
   ]
  },
  {
   "title": "Node CPU (avg. cores used)",
   "type": "timeseries",
   "description": "This calculates the average numbers of cores used by the ethrex node during the last minute.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"}[1m])",
     "legendFormat": "{{ instance }} CPU cores used"
    }
   ]
  },
  {
   "title": "Node Memory (RSS)",
   "type": "timeseries",
   "description": "This calculates the RSS memory for the ethrex node.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"}",
     "legendFormat": "{{ instance }} RSS"
    }
   ]
  },
  {
   "title": "Host CPU Utilization (%)",
   "type": "timeseries",
   "description": "This is the CPU utilization % of the host machine where the node is running. This was extracted from node_exporter.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by (instance) (rate(node_cpu_seconds_total{mode!=\"idle\", instance=~\"$instance(:\\\\d+)?$\"}[1m])) / sum by (instance) (rate(node_cpu_seconds_total{instance=~\"$instance(:\\\\d+)?$\"}[1m]))",
     "legendFormat": "{{ instance }} CPU Utilization"
    }
   ]
  },
  {
   "title": "Host Ram (GiB) — Used vs Total",
   "type": "timeseries",
   "description": "This is the RAM (used vs Total) of the host machine where the node is running. This was extracted from node_exporter and converted from bytes to GiB",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$instance(:\\\\d+)?$\"} - node_memory_MemAvailable_bytes{instance=~\"$instance(:\\\\d+)?$\"}) / (1024*1024*1024)",
     "legendFormat": "{{ instance }} Memory Used"
    }
   ]
  },
  {
   "title": "Block Building (WIP)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block building base_fee",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "Gwei" } },
     "targets": [
      {
       "expr": "block_building_base_fee{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"} / 1000000000",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Blockbuilding Ggas/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "si:Ggas/s" } },
     "targets": [
      {
       "expr": "gigagas_block_building{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"} - 0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Block building time taken in ms",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "block_building_ms{job=\"$job\", instance=~\"$instance(:\\\\d+)?$\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}