{
 "title": "Nethermind",
 "tags": [
  "Nethermind",
  "Execution",
  "Full node"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   { "name": "network", "label": "Network", "query": { "query": "label_values(Network)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values({Network=~\"$network\"},Instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nethermind_version{Instance=~\"$instance\"}",
     "legendFormat": "{{Instance}} - {{Network}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nethermind_version{Instance=~\"$instance\"}",
     "legendFormat": "{{Instance}} - {{Version}}"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nethermind_version{Instance=~\"$instance\"}",
     "legendFormat": "{{Instance}} - {{Runtime}}"
    }
   ]
  },
  {
   "title": "Sync Type",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nethermind_version{Instance=~\"$instance\"}",
     "legendFormat": "{{Instance}} - {{SyncType}}"
    }
   ]
  },
  {
   "title": "Pruning Mode",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nethermind_version{Instance=~\"$instance\"}",
     "legendFormat": "{{Instance}} - {{PruningMode}}"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nethermind_sync_time{Instance=~\"$instance\"}",
     "legendFormat": "{{Instance}}"
    }
   ]
  },
  {
   "title": "Nethermind Database Total Size",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nethermind_state_db_size{Instance=~\"$instance\"} + nethermind_code_db_size + nethermind_bloom_db_size + nethermind_cht_db_size + nethermind_blocks_db_size + nethermind_headers_db_size + nethermind_witness_db_size + nethermind_metadata_db_size + nethermind_receipts_db_size + nethermind_block_infos_db_size",
     "legendFormat": "{{Instance}} Total"
    }
   ]
  },
  {
   "title": "Nethermind Databases Sizes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_cht_db_size{Instance=~\"$instance\"})",
     "legendFormat": "{{Instance}} CHT"
    },
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_code_db_size{Instance=~\"$instance\"})",
     "legendFormat": "{{Instance}} Code"
    },
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_bloom_db_size{Instance=~\"$instance\"})",
     "legendFormat": "{{Instance}} Bloom"
    },
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_state_db_size{Instance=~\"$instance\"})",
     "legendFormat": "{{Instance}} State"
    },
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_blocks_db_size{Instance=~\"$instance\"})",
     "legendFormat": "{{Instance}} Blocks"
    },
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_headers_db_size{Instance=~\"$instance\"})",
     "legendFormat": "{{Instance}} Headers"
    },
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_witness_db_size{Instance=~\"$instance\"})",
     "legendFormat": "{{Instance}} Witness"
    },
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_metadata_db_size{Instance=~\"$instance\"})",
     "legendFormat": "{{Instance}} Metadata"
    },
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_receipts_db_size{Instance=~\"$instance\"})",
     "legendFormat": "{{Instance}} Receipts"
    },
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_block_infos_db_size{Instance=~\"$instance\"})",
     "legendFormat": "{{Instance}} Blocks Info"
    }
   ]
  },
  { "title": "Basic Parameters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Sync Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nethermind_sync_peers{Instance=~\"$instance\"}",
     "legendFormat": "{{Instance}}"
    }
   ]
  },
  {
   "title": "Block Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "nethermind_blocks{Instance=~\"$instance\"}",
     "legendFormat": "{{Instance}} "
    }
   ]
  },
  {
   "title": "Total difficulty",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "nethermind_total_difficulty{Instance=~\"$instance\"}",
     "legendFormat": "{{Instance}} "
    },
    {}
   ]
  },
  {
   "title": "Last difficulty",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "nethermind_last_difficulty{Instance=~\"$instance\"}",
     "legendFormat": "{{Instance}} "
    }
   ]
  },
  {
   "title": "Seconds per block",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "$__range_s/increase(nethermind_blocks{ Instance=~\"$instance\"}[$__range])",
     "legendFormat": "{{Instance}} "
    }
   ]
  },
  {
   "title": "Total difficulty diff",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "increase(nethermind_total_difficulty{ Instance=~\"$instance\"}[$__range])",
     "legendFormat": "{{Instance}} "
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(nethermind_json_rpc_bytes_sent{Instance=~\"$instance\"}[1m])*60",
     "legendFormat": "{{Instance}} RPC Sent"
    },
    {
     "expr": "rate(nethermind_json_rpc_bytes_received{Instance=~\"$instance\"}[1m])*60",
     "legendFormat": "{{Instance}} RPC Received"
    },
    {
     "expr": "rate(nethermind_discovery_bytes_received{Instance=~\"$instance\"}[1m])*60",
     "legendFormat": "{{Instance}} Dscv Sent"
    },
    {
     "expr": "rate(nethermind_discovery_bytes_sent{Instance=~\"$instance\"}[1m])*60",
     "legendFormat": "{{Instance}} Dscv Received"
    },
    {
     "expr": "rate(nethermind_p2pbytes_received{Instance=~\"$instance\"}[1m])*60",
     "legendFormat": "{{Instance}} P2P Received"
    },
    {
     "expr": "rate(nethermind_p2pbytes_sent{Instance=~\"$instance\"}[1m])*60",
     "legendFormat": "{{Instance}} P2P Sent"
    }
   ]
  },
  {
   "title": "Version",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_version{Instance=~\"$instance\"}) != 0",
     "legendFormat": "{{Instance}}"
    }
   ]
  },
  {
   "title": "Engine API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Execution Times",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_new_payload_execution_time{Instance=~\"$instance\"})",
       "legendFormat": "{{Instance}} New Payload"
      },
      {
       "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_forkchoice_upded_execution_time{Instance=~\"$instance\"})",
       "legendFormat": "{{Instance}} Forkchoice Update"
      }
     ]
    },
    {
     "title": "Counters",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "nethermind_get_payload_requests{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Get Payload Requests"
      },
      {
       "expr": "nethermind_number_of_transactions_in_get_payload{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Transaction Count in Get Payload"
      }
     ]
    }
   ]
  },
  {
   "title": "AuRa Specific",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Blocks Sealed (total)",
     "type": "stat",
     "description": "Total number of sealed blocks",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nethermind_blocks_sealed{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} "
      }
     ]
    },
    {
     "title": "Failed Block Seals (total)",
     "type": "stat",
     "description": "Total number of failed block seals",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nethermind_failed_block_seals{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} "
      }
     ]
    },
    {
     "title": "Aura Step",
     "type": "graph",
     "description": "Current AuRa step",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_au_ra_step{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} "
      }
     ]
    },
    {
     "title": "Blocks Production Indicator",
     "type": "stat",
     "description": "Indicator if blocks can be produced",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nethermind_can_produce_blocks{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} "
      }
     ]
    },
    {
     "title": "Reported Malicious Misbehaviour",
     "type": "stat",
     "description": "Number of reported malicious misbehaviour validators",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nethermind_reported_malicious_misbehaviour{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} "
      }
     ]
    },
    {
     "title": "Sealed Transactions",
     "type": "graph",
     "description": "Number of sealed transactions generated by engine",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_sealed_transactions{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} "
      }
     ]
    },
    {
     "title": "Reported Benign Misbehaviour",
     "type": "stat",
     "description": "Number of reported benign misbehaviour validators",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nethermind_reported_benign_misbehaviour{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} "
      }
     ]
    },
    {
     "title": "Validators Count",
     "type": "stat",
     "description": "Number of current AuRa validators",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "nethermind_validators_count{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} "
      }
     ]
    },
    {
     "title": "RANDAO Reveal Number",
     "type": "graph",
     "description": "RANDAO number of reveal number transactions",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_reveal_number{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} "
      }
     ]
    },
    {
     "title": "POSDAO Emit Initiate Change",
     "type": "graph",
     "description": "POSDAO number of emit init change transactions",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_emit_initiate_change{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} "
      }
     ]
    },
    {
     "title": "RANDAO Commit Hash Transaction",
     "type": "graph",
     "description": "RANDAO number of commit hash transactions",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_commit_hash_transaction{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_working_set_bytes{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Total Memory"
      },
      {
       "expr": "dotnet_total_memory_bytes{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Managed Memory"
      },
      {
       "expr": "dotnet_total_memory_bytes{Instance=~\"$instance\"} -   nethermind_memory_used_by_cache{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Managed Memory without pruning cache"
      },
      {
       "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_db_total_memory_size{Instance=~\"$instance\"})",
       "legendFormat": "{{Instance}} DB Total Memory"
      },
      {
       "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_db_block_cache_memory_size{Instance=~\"$instance\"})",
       "legendFormat": "{{Instance}} DB Blockcache"
      },
      {
       "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_db_index_filter_memory_size{Instance=~\"$instance\"})",
       "legendFormat": "{{Instance}} DB Index & Filters"
      },
      {
       "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_db_memtable_memory_size{Instance=~\"$instance\"})",
       "legendFormat": "{{Instance}} DB Memtables"
      }
     ]
    },
    {
     "title": "Time in GC",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "system_runtime_time_in_gc{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Time GC"
      }
     ]
    },
    {
     "title": "Memory Growth (per second)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "deriv(dotnet_total_memory_bytes{Instance=~\"$instance\"}[2m]) > 0",
       "legendFormat": "{{Instance}} Managed Memory",
       "target": "*.Nethermind_Runner.*.*.*.*.gauge.*.Process_Physical_Memory"
      }
     ]
    },
    {
     "title": "GC (per minute)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(dotnet_collection_count_total{generation=\"0\",Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Gen 0"
      },
      {
       "expr": "rate(dotnet_collection_count_total{generation=\"1\",Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Gen 1"
      },
      {
       "expr": "rate(dotnet_collection_count_total{generation=\"2\",Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Gen 2"
      },
      {
       "expr": "system_runtime_time_in_gc{generation=\"2\",Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} __auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Pruning",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Caching Efficiency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_loaded_from_db_nodes_count{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} DB"
      },
      {
       "expr": "nethermind_loaded_from_rlp_cache_nodes_count{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} RLP Cache"
      },
      {
       "expr": "nethermind_loaded_from_cache_nodes_count{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Node Cache"
      },
      {
       "expr": "nethermind_rlp_cache_hits{ Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} TrieStore RLP Cache Hits"
      }
     ]
    },
    {
     "title": "Pruning Cache",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "nethermind_memory_used_by_cache{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} "
      }
     ]
    },
    {
     "title": "Pruning Levels",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_committed_nodes_count{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Committed"
      },
      {
       "expr": "nethermind_persisted_node_count{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Persisted"
      },
      {
       "expr": "nethermind_cached_nodes_count{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Cached"
      },
      {
       "expr": "nethermind_replaced_nodes_count{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Replaced"
      },
      {
       "expr": "nethermind_pruned_persisted_nodes_count{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Pruned Persisted"
      },
      {
       "expr": "nethermind_pruned_transient_nodes_count{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Pruned Transient"
      }
     ]
    },
    {
     "title": "Times",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_snapshot_persistence_time{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Persistence"
      },
      {
       "expr": "nethermind_pruning_time{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Pruning"
      },
      {
       "expr": "nethermind_deep_pruning_time{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block processing time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_last_block_processing_time_in_ms{Instance=~\"$instance\"})",
       "legendFormat": "{{Instance}} Block time"
      }
     ]
    },
    {
     "title": "GasUsed",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_gas_used{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Block Gas"
      }
     ]
    },
    {
     "title": "Blocks (per second)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(nethermind_blocks{Instance=~\"$instance\"}[4m])*240.0",
       "legendFormat": "{{Instance}} Blocks"
      }
     ]
    },
    {
     "title": "Sync Peers",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short", "label": "Sync Peers" }
     ],
     "targets": [
      {
       "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_sync_peers{Instance=~\"$instance\"})",
       "legendFormat": "{{Instance}} Sync Peers"
      }
     ]
    },
    {
     "title": "State Synced (in bytes)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_state_synced{Instance=~\"$instance\"})",
       "legendFormat": "{{Instance}} State"
      },
      {
       "expr": "rate(nethermind_state_synced{Instance=~\"$instance\"}[60m])*3600",
       "legendFormat": "{{Instance}} State/h"
      },
      {
       "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_snap_state_synced{Instance=~\"$instance\"})",
       "legendFormat": "{{Instance}} SnapState"
      },
      {
       "expr": "rate(nethermind_snap_state_synced{Instance=~\"$instance\"}[60m])*3600",
       "legendFormat": "{{Instance}} SnapState/h"
      }
     ]
    },
    {
     "title": "SnapSync - Accounts, Storage and ByteCodes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_snap_synced_storage_slots{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Storage slots"
      },
      {
       "expr": "nethermind_snap_synced_accounts{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Accounts"
      },
      {
       "expr": "nethermind_snap_synced_codes{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Codes"
      }
     ]
    },
    {
     "title": "Fast Blocks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_fast_headers{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Headers"
      },
      {
       "expr": "nethermind_fast_bodies{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Bodies"
      },
      {
       "expr": "nethermind_fast_receipts{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Receipts"
      }
     ]
    },
    {
     "title": "Blocks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nethermind_blocks{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Block Number"
      }
     ]
    },
    {
     "title": "CPU time (tracks restarts)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{Instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{Instance}} CPU time"
      }
     ]
    }
   ]
  },
  {
   "title": "JSON RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "JSON RPC (per minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_json_rpc_successes{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} RPC Successes"
      },
      {
       "expr": "rate(nethermind_json_rpc_errors{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} RPC Errors"
      },
      {
       "expr": "rate(nethermind_json_rpc_request_deserialization_failures{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Deserialization Failures"
      },
      {
       "expr": "rate(nethermind_json_rpc_invalid_requests{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Invalid Requests"
      }
     ]
    },
    {
     "title": "JSON RPC (total)",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "nethermind_json_rpc_requests{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} RPC Requests"
      },
      {
       "expr": "nethermind_json_rpc_successes{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} RPC Successes"
      },
      {
       "expr": "nethermind_json_rpc_errors{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} RPC Errors"
      },
      {
       "expr": "nethermind_json_rpc_request_deserialization_failures{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Deserialization Failures"
      },
      {
       "expr": "nethermind_json_rpc_invalid_requests{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Invalid Requests"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections (per minute)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_incoming_connections{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Incoming Connections"
      },
      {
       "expr": "rate(nethermind_outgoing_connections{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Outgoing Connections"
      },
      {
       "expr": "rate(nethermind_handshakes{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Handshakes"
      },
      {
       "expr": "rate(nethermind_hellos_sent{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Hellos Sent"
      },
      {
       "expr": "rate(nethermind_hellos_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Hellos Received"
      },
      {
       "expr": "rate(nethermind_statuses_sent{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Statuses Sent"
      },
      {
       "expr": "rate(nethermind_statuses_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Statuses Received"
      }
     ]
    },
    {
     "title": "Pending Txs (per minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_pending_transactions_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Received"
      },
      {
       "expr": "rate(nethermind_pending_transactions_known{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Already Known"
      },
      {
       "expr": "rate(nethermind_pending_transactions_discarded{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Discarded"
      },
      {
       "expr": "rate(nethermind_pending_transactions_too_far_in_future{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Too far in future"
      },
      {
       "expr": "rate(nethermind_pending_transactions_too_low_fee{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Too low fee"
      },
      {
       "expr": "rate(nethermind_pending_transactions_added{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Added (all)"
      },
      {
       "expr": "rate(nethermind_pending1559transactions_added{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Added (1559)"
      },
      {
       "expr": "rate(nethermind_pending_transactions_evicted{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Evicted"
      },
      {
       "expr": "rate(nethermind_pending_transactions_sent{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Sent txs"
      },
      {
       "expr": "rate(nethermind_pending_transactions_hashes_sent{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Sent hashes"
      }
     ]
    },
    {
     "title": "Disconnects (per minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_too_many_peers_disconnects{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Too Many Peers"
      },
      {
       "expr": "rate(nethermind_client_quitting_disconnects{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Client Quitting"
      },
      {
       "expr": "rate(nethermind_receive_message_timeout_disconnects{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Receive Timeouts"
      },
      {
       "expr": "rate(nethermind_already_connected_disconnects{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Already Connected"
      },
      {
       "expr": "rate(nethermind_breach_of_protocol_disconnects{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Breach of Protocol"
      },
      {
       "expr": "rate(nethermind_incompatible_p2pdisconnects{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Incompatible P2P"
      },
      {
       "expr": "rate(nethermind_null_node_identity_disconnects{_Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Null Identity"
      },
      {
       "expr": "rate(nethermind_unexpected_identity_disconnects{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Unexpected Identity"
      },
      {
       "expr": "rate(nethermind_useless_peer_disconnects{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Useless Peer"
      },
      {
       "expr": "rate(nethermind_diconnect_requested_disconnects{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Requested"
      },
      {
       "expr": "rate(nethermind_tcp_subsystem_error_disconnects{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} TCP Error"
      },
      {
       "expr": "rate(nethermind_same_as_self_disconnects{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Same as Self"
      },
      {
       "expr": "rate(nethermind_other_disconnects{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Other"
      }
     ]
    },
    {
     "title": "Eth62, Eth63, Eth65, Eth66 (per minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_eth62get_block_headers_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} GetBlockHeaders eth62"
      },
      {
       "expr": "rate(nethermind_eth62block_headers_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} BlockHeaders eth62"
      },
      {
       "expr": "rate(nethermind_eth62get_block_bodies_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} GetBlockBodies eth62"
      },
      {
       "expr": "rate(nethermind_eth62block_bodies_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} BlockBodies eth62"
      },
      {
       "expr": "rate(nethermind_eth62transactions_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Txs received eth62"
      },
      {
       "expr": "rate(nethermind_eth65new_pooled_transaction_hashes_sent{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} TxHashes sent eth65"
      },
      {
       "expr": "rate(nethermind_eth65new_pooled_transaction_hashes_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} TxHashes received eth65"
      },
      {
       "expr": "rate(nethermind_eth65get_pooled_transactions_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Txs requests received eth65"
      },
      {
       "expr": "rate(nethermind_eth65get_pooled_transactions_requested{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Txs requested eth65"
      },
      {
       "expr": "rate(nethermind_eth65pooled_transactions_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Txs received eth65"
      },
      {
       "expr": "rate(nethermind_eth62new_block_hashes_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} NewBlockHashes eth62"
      },
      {
       "expr": "rate(nethermind_eth62new_block_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} NewBlock eth62"
      },
      {
       "expr": "rate(nethermind_eth63get_node_data_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} GetNodeData eth63"
      },
      {
       "expr": "rate(nethermind_eth63node_data_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} NodeData eth63"
      },
      {
       "expr": "rate(nethermind_eth63get_receipts_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} GetReceipts eth63"
      },
      {
       "expr": "rate(nethermind_eth63receipts_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Receipts eth63"
      },
      {
       "expr": "rate(nethermind_eth66get_block_headers_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} GetBlockHeaders eth66"
      },
      {
       "expr": "rate(nethermind_eth66block_headers_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} BlockHeaders eth66"
      },
      {
       "expr": "rate(nethermind_eth66get_block_bodies_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} GetBlockBodies eth66"
      },
      {
       "expr": "rate(nethermind_eth66block_bodies_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} BlockBodies eth66"
      },
      {
       "expr": "rate(nethermind_eth66get_pooled_transactions_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Txs requests received eth66"
      },
      {
       "expr": "rate(nethermind_eth66get_pooled_transactions_requested{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Txs requested eth66"
      },
      {
       "expr": "rate(nethermind_eth66pooled_transactions_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Txs received eth66"
      },
      {
       "expr": "rate(nethermind_eth66get_node_data_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} GetNodeData eth66"
      },
      {
       "expr": "rate(nethermind_eth66node_data_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} NodeData eth66"
      },
      {
       "expr": "rate(nethermind_eth66get_receipts_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} GetReceipts eth66"
      },
      {
       "expr": "rate(nethermind_eth66receipts_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Receipts eth66"
      }
     ]
    },
    {
     "title": "Snap Sync (per minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_snap_get_account_range_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} GetAccountRange received"
      },
      {
       "expr": "rate(nethermind_snap_get_account_range_sent{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} GetAccountRange sent"
      },
      {
       "expr": "rate(nethermind_snap_account_range_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} AccountRange received"
      },
      {
       "expr": "rate(nethermind_snap_get_storage_ranges_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} GetStorageRanges received"
      },
      {
       "expr": "rate(nethermind_snap_get_storage_ranges_sent{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} GetStorageRanges sent"
      },
      {
       "expr": "rate(nethermind_snap_storage_ranges_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} StorageRanges received"
      },
      {
       "expr": "rate(nethermind_snap_get_byte_codes_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} GetByteCodes received"
      },
      {
       "expr": "rate(nethermind_snap_get_byte_codes_sent{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} GetByteCodes sent"
      },
      {
       "expr": "rate(nethermind_snap_byte_codes_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} ByteCodes received"
      },
      {
       "expr": "rate(nethermind_snap_get_trie_nodes_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} GetTriinstances received"
      },
      {
       "expr": "rate(nethermind_snap_get_trie_nodes_sent{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} GetTriinstances sent"
      },
      {
       "expr": "rate(nethermind_snap_trie_nodes_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Triinstances received"
      }
     ]
    }
   ]
  },
  {
   "title": "Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Receipts DB",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_receipts_db_reads{Instance=~\"$instance\"}[10s])",
       "legendFormat": "{{Instance}} Reads"
      },
      {
       "expr": "rate(nethermind_receipts_db_writes{Instance=~\"$instance\"}[10s])",
       "legendFormat": "{{Instance}} Writes"
      }
     ]
    },
    {
     "title": "Code DB",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(nethermind_code_db_reads{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Reads"
      },
      {
       "expr": "rate(nethermind_code_db_writes{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Writes"
      }
     ]
    },
    {
     "title": "State Tree",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(nethermind_state_tree_cache_reads{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Cache Reads"
      },
      {
       "expr": "rate(nethermind_read_only_state_tree_cache_reads{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Reader Cache"
      },
      {
       "expr": "rate(nethermind_state_tree_reads{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Reads"
      },
      {
       "expr": "rate(nethermind_read_only_state_tree_reads{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Reader Reads"
      },
      {
       "expr": "rate(nethermind_state_tree_writes{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Writes"
      }
     ]
    },
    {
     "title": "Block Info DB",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "rate(nethermind_block_infos_db_reads{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Reads"
      },
      {
       "expr": "rate(nethermind_block_infos_db_writes{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Writes"
      }
     ]
    },
    {
     "title": "State DB",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_state_db_reads{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Reads"
      },
      {
       "expr": "rate(nethermind_state_db_writes{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Writes"
      },
      {
       "expr": "rate(nethermind_state_db_in_pruning_writes{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Pruning Writes"
      }
     ]
    },
    {
     "title": "Storage Tree",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(nethermind_storage_tree_cache_reads{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Cached Reads"
      },
      {
       "expr": "rate(nethermind_storage_tree_reads{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Reads"
      },
      {
       "expr": "rate(nethermind_read_only_storage_tree_reads{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Reader Reads"
      },
      {
       "expr": "rate(nethermind_storage_tree_writes{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Writes"
      }
     ]
    },
    {
     "title": "Trie Operations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(nethermind_tree_node_rlp_decodings{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} RLP.Encode"
      },
      {
       "expr": "rate(nethermind_tree_node_rlp_encodings{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} RLP.Decode"
      },
      {
       "expr": "rate(nethermind_tree_node_hash_calculations{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Keccak"
      }
     ]
    },
    {
     "title": "Other DB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_other_db_reads{Instance=~\"$instance\"}[10s])",
       "legendFormat": "{{Instance}} Reads"
      },
      {
       "expr": "rate(nethermind_other_db_writes{Instance=~\"$instance\"}[10s])",
       "legendFormat": "{{Instance}} Writes"
      }
     ]
    },
    {
     "title": "Blocks DB (per minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_blocks_db_reads{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Reads"
      },
      {
       "expr": "rate(nethermind_blocks_db_writes{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Writes"
      }
     ]
    },
    {
     "title": "Header DB (per minute)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_header_db_reads{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Reads"
      },
      {
       "expr": "rate(nethermind_header_db_writes{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} Writes"
      }
     ]
    }
   ]
  },
  {
   "title": "TxPool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tx Count",
     "type": "graph",
     "description": "Information about incoming transactions",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nethermind_transaction_count{Instance=~\"$instance\"}",
       "legendFormat": "{{Instance}} Count"
      }
     ]
    },
    {
     "title": "DarkPool",
     "type": "graph",
     "description": "Unknown transactions in blocks",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_dark_pool_ratio_level1{Instance=~\"$instance\"})",
       "legendFormat": "{{Instance}} Level1 (not known)"
      },
      {
       "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_dark_pool_ratio_level2{Instance=~\"$instance\"})",
       "legendFormat": "{{Instance}} level2 (not pending)"
      }
     ]
    },
    {
     "title": "1559-type transactions ratio",
     "type": "timeseries",
     "description": "Ratio of 1559-type transactions in the block.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max without (BuildTimestamp,Commit,Version) (nethermind_eip1559transactions_ratio{Instance=~\"$instance\"})",
       "legendFormat": "{{Instance}} "
      }
     ]
    },
    {
     "title": "Incoming transactions",
     "type": "graph",
     "description": "Information about incoming transactions",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nethermind_pending_transactions_received{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} received"
      },
      {
       "expr": "rate(nethermind_pending_transactions_discarded{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} discarded"
      },
      {
       "expr": "rate(nethermind_pending_transactions_known{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} discarded already known"
      },
      {
       "expr": "rate(nethermind_pending_transactions_too_low_fee{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} discarded fee too low"
      },
      {
       "expr": "rate(nethermind_pending_transactions_added{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} added"
      },
      {
       "expr": "rate(nethermind_pending_transactions_evicted{Instance=~\"$instance\"}[1m])*60",
       "legendFormat": "{{Instance}} evicted"
      }
     ]
    }
   ]
  }
 ]
}