#!/usr/bin/env bash
# =============================================================================
# import-validators-nimbus.sh
# Imports all Ethereum validator keystores into Nimbus,
# automatically injecting the password from the matching .txt file.
#
# Each keystore-N.json has a matching keystore-N.txt with its own password,
# as generated by the Obol cluster creation process.
#
# Usage:
#   chmod +x import-validators-nimbus.sh
#   ./import-validators-nimbus.sh
#
# Requirements:
#   - expect  (install with: sudo apt-get install expect)
#   - nimbus_beacon_node in PATH
# =============================================================================

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
KEYS_DIR="/home/ethereum/.charon/validator_keys"
NIMBUS_DATADIR="/home/ethereum/.nimbus-validator-obol-lido"
# ─────────────────────────────────────────────────────────────────────────────

if ! command -v expect &>/dev/null; then
  echo "[INFO] 'expect' not found — installing via apt..."
  sudo apt-get update -qq && sudo apt-get install -y expect
  if ! command -v expect &>/dev/null; then
    echo "[ERROR] Failed to install 'expect'. Install it manually: sudo apt-get install expect"
    exit 1
  fi
  echo "[INFO] 'expect' installed successfully."
fi

if ! command -v nimbus_beacon_node &>/dev/null; then
  echo "[ERROR] 'nimbus_beacon_node' binary not found in PATH."
  exit 1
fi

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

mapfile -t KEYSTORES < <(find "$KEYS_DIR" -maxdepth 1 -name "keystore-*.json" | sort)

if [[ ${#KEYSTORES[@]} -eq 0 ]]; then
  echo "[ERROR] No keystore-*.json files found in: $KEYS_DIR"
  exit 1
fi

echo "══════════════════════════════════════════════════════"
echo "  Nimbus Validator Import"
echo "  Keys directory : $KEYS_DIR"
echo "  Data dir       : $NIMBUS_DATADIR"
echo "  Keystores found: ${#KEYSTORES[@]}"
echo "══════════════════════════════════════════════════════"

SUCCESS=0
FAILED=0
SKIPPED=0

for KEYSTORE_PATH in "${KEYSTORES[@]}"; do
  KEYSTORE_FILE=$(basename "$KEYSTORE_PATH")
  BASE="${KEYSTORE_FILE%.json}"
  PASSWORD_FILE="$KEYS_DIR/${BASE}.txt"

  echo ""
  echo "──────────────────────────────────────────────────────"
  echo "  Keystore : $KEYSTORE_FILE"

  if [[ ! -f "$PASSWORD_FILE" ]]; then
    echo "  [SKIP] No matching password file: ${BASE}.txt"
    (( SKIPPED++ )) || true
    continue
  fi

  PASSWORD=$(< "$PASSWORD_FILE")

  if [[ -z "$PASSWORD" ]]; then
    echo "  [SKIP] Password file is empty: ${BASE}.txt"
    (( SKIPPED++ )) || true
    continue
  fi

  echo "  Password : loaded from ${BASE}.txt"

  rm -f "$TMPDIR"/*.json
  cp "$KEYSTORE_PATH" "$TMPDIR/"

  IMPORT_OUTPUT=$(expect -c "
    log_user 1
    set timeout 60
    spawn nimbus_beacon_node deposits import $TMPDIR \
      --data-dir=$NIMBUS_DATADIR
    expect {
      -re {(Enter|enter|Password|password).*:} {
        send \"${PASSWORD}\r\"
        exp_continue
      }
      -re {(Repeat|repeat|Confirm|confirm).*:} {
        send \"${PASSWORD}\r\"
        exp_continue
      }
      eof
    }
  " 2>&1) && RC=0 || RC=$?

  if echo "$IMPORT_OUTPUT" | grep -qiE "imported|success|already exists|duplicate"; then
    echo "  [OK] Import successful"
    (( SUCCESS++ )) || true
  else
    echo "  [FAIL] Import may have failed (exit code: $RC)"
    echo "  ── Output ──────────────────────────────────────────"
    echo "$IMPORT_OUTPUT" | sed 's/^/    /'
    echo "  ────────────────────────────────────────────────────"
    (( FAILED++ )) || true
  fi

done

echo ""
echo "══════════════════════════════════════════════════════"
echo "  Import Summary"
echo "  ✔ Success : $SUCCESS"
echo "  ✗ Failed  : $FAILED"
echo "  ⊘ Skipped : $SKIPPED"
echo "══════════════════════════════════════════════════════"

[[ $FAILED -gt 0 ]] && exit 1
exit 0
