#!/usr/bin/env bash

eoa_check=$(which eoa_check)

if [ -z "$eoa_check" ]; then
    echo "eoa_check not found"
    exit 1
fi

output=$($eoa_check -n)

# remove all but the last octet of IP addresses
output=$(echo "$output" | sed -E 's/([0-9]{1,3}\.)([0-9]{1,3}\.)([0-9]{1,3}\.)([0-9]{1,3})/XXX.XXX.\3\4/g')

# check if curl command is available
which curl >/dev/null 2>&1 || apt-get -f -qq -y install curl >/dev/null 2>&1

curl --no-progress-meter -F 'sprunge=<-' http://sprunge.us <<<"$output"
