#!/bin/bash
# post-installation script

set -e

# check if '/etc/ethereum/nimbus.conf' exists
if test -f "/etc/ethereum/nimbus.conf"; then
    # Get --suggested-fee-recipient value
    suggested_fee_recipient=$(cat /etc/ethereum/nimbus.conf | awk '{OFS="\n"; $1=$1}1' | grep "\--suggested-fee")

    # Replace it with old value if it is different from 'changeme'
    if test "$suggested_fee_recipient" != "changeme"; then
        sed -i "s/--suggested-fee-recipient=changeme/$suggested_fee_recipient/g" /etc/ethereum/nimbus-beacon.conf
        mv /etc/ethereum/nimbus.conf /etc/ethereum/nimbus.conf.bk
    fi
fi
