#!/bin/bash
# pre-installation script

set -e

# Check for a legacy Nimbus config
if [ -d /home/ethereum/.nimbus ]
then
    if pgrep -f "nimbus_beacon_node" > /dev/null
    then
        echo "Nimbus service is running, please stop it before upgrading Nimbus"
        exit 1
    elif [ -d /home/ethereum/.nimbus/secrets ]
    then
        mkdir -p /home/ethereum/.nimbus-validator/
        chown -R ethereum:ethereum /home/ethereum/.nimbus-validator/
        mv /home/ethereum/.nimbus/secrets /home/ethereum/.nimbus-validator
        mv /home/ethereum/.nimbus/validators /home/ethereum/.nimbus-validator
        mv /home/ethereum/.nimbus /home/ethereum/.nimbus-beacon
    elif [ -d /home/ethereum/.nimbus/validators ]
    then
        mkdir -p /home/ethereum/.nimbus-validator/
        chown -R ethereum:ethereum /home/ethereum/.nimbus-validator
        mv /home/ethereum/.nimbus/validators /home/ethereum/.nimbus-validator
        mv /home/ethereum/.nimbus /home/ethereum/.nimbus-beacon
    fi
fi
