name: Update Package Status

# Controls when the action will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs on a schedule (this example runs at 03:00 UTC every day)
  schedule:
    - cron: '0 3 * * *'

jobs:
  update-status:
    runs-on: ubuntu-latest
    # Set permissions for the job to allow it to write to the repository
    permissions:
      contents: write

    steps:
      # 1. Checks out your repository's code
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Run the script to generate the status file
      #    -t uses the automatically provided GITHUB_TOKEN to avoid API rate limits
      #    -m generates the STATUS.md file
      - name: Run version check script
        run: |
          bash ./tools/get_versions.sh -m STATUS.md -t ${{ secrets.REPO_GITHUB_TOKEN }}
      
      # 3. Commits the changes to the repository if the file has been modified
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs(status): Auto-update package versions'
          file_pattern: STATUS.md
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'