{
 "title": "Bedrock Networks",
 "tags": [ "public" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Rollup nodes - Block numbers",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "op_node_default_refs_number{layer=\"l1\",type=\"l1_head\"}",
     "legendFormat": "{{namespace}}   - L1 head"
    },
    {
     "expr": "op_node_default_refs_number{layer=\"l2\",type=\"l2_safe\"}",
     "legendFormat": "{{namespace}}   - L2 safe"
    },
    {
     "expr": "op_node_default_refs_number{layer=\"l2\",type=\"l2_unsafe\"}",
     "legendFormat": "{{namespace}}   - L2 unsafe"
    },
    {
     "expr": "op_node_default_refs_number{layer=\"l1_origin\",type=\"l2_safe\"}",
     "legendFormat": "{{namespace}} - L1 origin of L2 safe"
    },
    {
     "expr": "op_node_default_refs_number{layer=\"l1_origin\",type=\"l2_unsafe\"}",
     "legendFormat": "{{namespace}} - L1 origin of L2 unsafe"
    }
   ]
  },
  {
   "title": "Rollup nodes - Block latency (seen - timestamp)",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "-min_over_time(op_node_default_refs_latency[$__interval])",
     "legendFormat": "{{namespace}} {{type}}"
    }
   ]
  },
  {
   "title": "Unsafe-block processing time / real time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(op_node_default_events_process_time{event_type=\"process-unsafe-payload\"}[$__rate_interval])",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Rollup nodes - Block timestamp",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "last_over_time(op_node_default_refs_time[$__interval])",
     "legendFormat": "{{namespace}} {{type}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "targets": [
    { "expr": "op_node_default_p2p_peer_count", "legendFormat": "{{namespace}}" }
   ]
  },
  {
   "title": "Rollup nodes - Block hashes",
   "type": "status-history",
   "gridPos": { "h": 39, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "op_node_default_refs_hash{layer=\"l1\", type=\"l1_head\"}",
     "legendFormat": "{{namespace}}   -  L1 head"
    },
    {
     "expr": "op_node_default_refs_hash{layer=\"l1\", type=\"l1_safe\"}",
     "legendFormat": "{{namespace}}   -   L1 safe"
    },
    {
     "expr": "op_node_default_refs_hash{layer=\"l1\", type=\"l1_finalized\"}",
     "legendFormat": "{{namespace}}   -  L1 finalized"
    },
    {
     "expr": "op_node_default_refs_hash{layer=\"l2\", type=\"l2_unsafe\"}",
     "legendFormat": "{{namespace}}   -  L2 unsafe"
    },
    {
     "expr": "op_node_default_refs_hash{layer=\"l2\", type=\"l2_safe\"}",
     "legendFormat": "{{namespace}}   -  L2 safe"
    },
    {
     "expr": "op_node_default_refs_hash{layer=\"l2\", type=\"l2_finalized\"}",
     "legendFormat": "{{namespace}}   -  L2 finalized"
    },
    {
     "expr": "op_node_default_refs_hash{layer=\"l1_origin\", type=\"l2_unsafe\"}",
     "legendFormat": "{{namespace}}   -  L2 unsafe L1 origin"
    },
    {
     "expr": "op_node_default_refs_hash{layer=\"l1_origin\", type=\"l2_safe\"}",
     "legendFormat": "{{namespace}}   -  L2 safe L1 origin"
    },
    {
     "expr": "op_node_default_refs_hash{layer=\"l1_origin\", type=\"l2_finalized\"}",
     "legendFormat": "{{namespace}}   -  L2 finalized L1 origin"
    },
    {
     "expr": "op_node_default_refs_hash{layer=\"l1\", type=\"l1_derived\"}",
     "legendFormat": "{{namespace}}   -  L1 derived input"
    }
   ]
  }
 ]
}