{
 "title": "Bedrock P2P",
 "tags": [ "public" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Peer Count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "op_node_default_p2p_peer_count", "legendFormat": "{{namespace}}" }
   ]
  },
  {
   "title": "Peers Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expr": "op_node_default_p2p_peer_count", "legendFormat": "{{app_kubernetes_io_instance}}" }
   ]
  },
  {
   "title": "Gossip Events/s [5m]",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(op_node_default_p2p_gossip_events_total[5m])",
     "legendFormat": "{{namespace}} - {{type}}"
    }
   ]
  },
  {
   "title": "Bandwidth In [5m]",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(op_node_default_p2p_bandwidth_bytes_total[5m])",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Bandwidth Out [5m]",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(op_node_default_p2p_bandwidth_bytes_total{ direction=\"out\"}[5m])",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}