{
 "title": "Bedrock Nodes",
 "tags": [ "public" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Nodes",
    "query": {
     "query": "label_values(op_node_default_up,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Node version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "op_node_default_info", "legendFormat": "version" }
   ]
  },
  {
   "title": "Required protocol version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_protocol_versions",
     "legendFormat": "version"
    }
   ]
  },
  {
   "title": "op-node supported protocol version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_protocol_versions",
     "legendFormat": "version"
    }
   ]
  },
  {
   "title": "Last Reorg",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "op_node_default_last_pipeline_reset_unix * 1000"
    }
   ]
  },
  {
   "title": "Seconds per block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "1/max(rate(op_node_default_refs_number{type=\"l1_head\", layer=\"l1\"}[$__interval]))",
     "legendFormat": "L1"
    },
    {
     "expr": "1/max(rate(op_node_default_refs_number{type=\"l2_safe\", layer=\"l2\"}[10m]))",
     "legendFormat": "Safe L2"
    },
    {
     "expr": "1/max(rate(op_node_default_refs_number{type=\"l2_unsafe\", layer=\"l2\"}[$__interval]))",
     "legendFormat": "Unsafe L2"
    }
   ]
  },
  {
   "title": "Recommended protocol version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_node_default_protocol_versions",
     "legendFormat": "version"
    }
   ]
  },
  {
   "title": "L2 Unsafe L1 Origin",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{type=\"l2_unsafe\", layer=\"l1_origin\"})"
    }
   ]
  },
  {
   "title": "Node Online",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(op_node_default_up)" }
   ]
  },
  {
   "title": "L1 Head (a.k.a. unsafe)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_refs_number{type=\"l1_head\", layer=\"l1\"})",
     "legendFormat": "L1"
    }
   ]
  },
  {
   "title": "RPC methods requests / second (moving avg.)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (method) (rate(op_node_default_rpc_client_requests_total[$__rate_interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Derivation Idle",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_derivation_idle)"
    }
   ]
  },
  {
   "title": "Sequencing Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(op_node_default_sequencing_errors_total)"
    }
   ]
  },
  {
   "title": "Sequencer Block building time diff (50ms sealing expected)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(op_node_default_sequencer_building_diff_seconds_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Engine API - newPayload time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(increase(op_node_default_rpc_client_request_duration_seconds_bucket{method=~\"engine_newPayloadV[0-9]\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "max by (job) (process_resident_memory_bytes)",
     "legendFormat": "{{job}} Resident"
    },
    {
     "expr": "max by (job) (process_virtual_memory_bytes)",
     "legendFormat": "{{job}} Virtual"
    }
   ]
  },
  {
   "title": "Peers and streams",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "max(op_node_default_p2p_peer_count)",
     "legendFormat": "peers"
    },
    {
     "expr": "max(op_node_default_p2p_stream_count)",
     "legendFormat": "libp2p streams"
    }
   ]
  },
  {
   "title": "Peer Scores [Buckets]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "rate(op_node_default_peer_scores_bucket{type=\"total\"}[10m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Peer Scores [Buckets]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "rate(op_node_default_peer_scores_bucket{type=\"total\"}[10m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "gossip events rate / min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "sum by (type) (rate(op_node_default_p2p_gossip_events_total[$__interval])) * 60",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}