{
 "title": "Op - Challenger",
 "tags": [
  "optimism",
  "challenger"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Challenger Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"op-challenger\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Game Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 1 },
   "targets": [
    { "expr": "op_challenger_game_status", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Resolutions (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "rate(op_challenger_resolves_total[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}