{
 "title": "op-node rollup events",
 "tags": [ "public" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Events processed per second",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(op_node_default_events_processed[$__rate_interval])",
     "legendFormat": "{{deriver}} {{event_type}}"
    }
   ]
  },
  {
   "title": "Processing time / real time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(op_node_default_events_process_time[$__rate_interval])",
     "legendFormat": "{{deriver}} {{event_type}}"
    }
   ]
  },
  {
   "title": "Processing time / real time, by Deriver",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(op_node_default_events_process_time[$__rate_interval])) by (deriver)",
     "legendFormat": "{{deriver}}"
    }
   ]
  },
  {
   "title": "Events emitted per second, by Emitter",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(op_node_default_events_emitted[$__rate_interval])) by (emitter)",
     "legendFormat": "{{emitter}}"
    }
   ]
  },
  {
   "title": "Events emitted per second, by Event-type",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(op_node_default_events_emitted[$__rate_interval])) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  }
 ]
}