{
 "title": "Op - Dispute Monitor",
 "description": "Display metrics from op-dispute-mon (Local/Docker)",
 "tags": [ "public" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Monitored Games",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(op_dispute_mon_games_agreement)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(op_dispute_mon_games_agreement{completion=\"in_progress\"})",
     "legendFormat": "In Progress"
    },
    {
     "expr": "sum(op_dispute_mon_ignored_games)",
     "legendFormat": "Ignored"
    }
   ]
  },
  {
   "title": "Incorrect Forecast",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(op_dispute_mon_games_agreement{result_correctness=\"incorrect\", completion=\"in_progress\"})",
     "legendFormat": "Forecast"
    }
   ]
  },
  {
   "title": "Last Output Root Fetch Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(time() - op_dispute_mon_last_output_fetch)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Invalid Proposal",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(time() - op_dispute_mon_latest_proposal{root_agreement=\"disagree\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "op_dispute_mon_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Incorrect Result",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(op_dispute_mon_games_agreement{result_correctness=\"incorrect\", completion=\"complete\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Up",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "min(op_dispute_mon_up{namespace=\"op-dispute-mon\"}) > 0",
     "legendFormat": "1 if dispute mon is up"
    }
   ]
  },
  { "title": "Game Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Games",
   "type": "timeseries",
   "description": "Tracked games broken down by actual status",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace) (op_dispute_mon_games_agreement{completion=\"in_progress\"})",
     "legendFormat": "In Progress"
    },
    {
     "expr": "sum by (cluster, namespace) (op_dispute_mon_games_agreement{completion=\"complete\", status=~\".*challenger_wins\"})",
     "legendFormat": "Challenger Wins"
    },
    {
     "expr": "sum by (cluster, namespace) (op_dispute_mon_games_agreement{completion=\"complete\", status=~\".*defender_wins\"})",
     "legendFormat": "Defender Wins"
    },
    {
     "expr": "sum by (cluster, namespace) (op_dispute_mon_ignored_games)",
     "legendFormat": "Ignored"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "{job=\"op-dispute-mon\"} |= `` | logfmt | lvl =~ `err?or` | label_format level=lvl"
    }
   ]
  },
  {
   "title": "Warn Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "{job=\"op-dispute-mon\"} |= `` | logfmt | lvl = `warn` | label_format level=lvl"
    }
   ]
  },
  {
   "title": "Full Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "{job=\"op-dispute-mon\"} |= `` | logfmt | label_format level=lvl"
    }
   ]
  }
 ]
}