#!/usr/bin/env bash
# =============================================================================
# import-validators-teku.sh — Import Obol DVT keystores into Teku VC.
#
# Designed for Ethereum on ARM / Obol DVT clusters.
# Keystores live in /home/ethereum/.charon/validator_keys/
#
# Each keystore-N.json has a matching keystore-N.txt with its own password,
# as generated by the Obol cluster creation process.
#
# Teku reads keystores from --validator-keys=<keystore-dir>:<password-dir>
# so this script copies keystores and password files to dedicated directories.
#
# Usage:
#   bash import-validators-teku.sh
#   bash import-validators-teku.sh \
#       --keys-dir      /home/ethereum/.charon/validator_keys \
#       --keystore-dir  /home/ethereum/.teku-validator-obol/keys \
#       --password-dir  /home/ethereum/.teku-validator-obol/passwords
# =============================================================================
set -euo pipefail

KEYS_DIR="/home/ethereum/.charon/validator_keys"
KEYSTORE_DIR="/home/ethereum/.teku-validator-obol/keys"
PASSWORD_DIR="/home/ethereum/.teku-validator-obol/passwords"
SERVICE=""
AUTO_RESTART=true

SEP="────────────────────────────────────────────"

usage() {
    cat << 'EOF'
Usage: bash import-validators-teku.sh [OPTIONS]

Options:
  --keys-dir     <path>  Keystore directory (default: ~/.charon/validator_keys)
  --keystore-dir <path>  Teku keys dir     (default: ~/.teku-validator-obol/keys)
  --password-dir <path>  Teku passwords dir (default: ~/.teku-validator-obol/passwords)
  --service      <name>  Systemd service name (auto-detected if not set)
  --no-restart           Do not restart service after import
  --help                 Show this help
EOF
    exit 0
}

while [ $# -gt 0 ]; do
    case "$1" in
        --keys-dir)     KEYS_DIR="$2";     shift 2 ;;
        --keystore-dir) KEYSTORE_DIR="$2"; shift 2 ;;
        --password-dir) PASSWORD_DIR="$2"; shift 2 ;;
        --service)      SERVICE="$2";      shift 2 ;;
        --no-restart)   AUTO_RESTART=false; shift ;;
        --help|-h)      usage ;;
        *) echo "Unknown option: $1"; usage ;;
    esac
done

[ ! -d "$KEYS_DIR" ] && { echo "ERROR: Keys dir not found: $KEYS_DIR"; exit 1; }

KEYSTORE_COUNT=$(find "$KEYS_DIR" -maxdepth 1 -name '*.json' 2>/dev/null | wc -l)
[ "$KEYSTORE_COUNT" -eq 0 ] && { echo "ERROR: No keystores found in $KEYS_DIR"; exit 1; }

if [ -z "$SERVICE" ]; then
    for svc in teku-validator-obol-lido teku-validator-obol \
               teku-validator-lido teku-validator teku; do
        systemctl list-units --full --all 2>/dev/null | grep -q "${svc}.service" && \
            { SERVICE="$svc"; break; }
    done
    [ -z "$SERVICE" ] && AUTO_RESTART=false
fi

echo ""
echo "$SEP"
echo "  Teku Validator Key Import"
echo "$SEP"
echo "  Keys src     : $KEYS_DIR ($KEYSTORE_COUNT keystore(s))"
echo "  Keystore dir : $KEYSTORE_DIR"
echo "  Password dir : $PASSWORD_DIR"
[ -n "$SERVICE" ] && echo "  Service      : $SERVICE"
echo "$SEP"
echo ""
echo "⚠️  SLASHING SAFETY — read before proceeding:"
echo "   1. Ensure the OLD validator is STOPPED."
echo "   2. Wait at least 2 epochs (~13 min) after stopping it."
echo "   3. NEVER run two validator instances with the same keys."
echo ""
read -rp "Type 'yes' to continue: " confirm
[ "$confirm" = "yes" ] || { echo "Aborted."; exit 0; }

if [ -n "$SERVICE" ] && systemctl is-active --quiet "$SERVICE" 2>/dev/null; then
    echo ""
    echo "--- Stopping $SERVICE ---"
    sudo systemctl stop "$SERVICE"
    echo "  ✅ Stopped"
    sleep 2
fi

echo ""
echo "--- Setting up Teku directories ---"
mkdir -p "$KEYSTORE_DIR" "$PASSWORD_DIR"
chmod 700 "$KEYSTORE_DIR" "$PASSWORD_DIR"
echo "  ✅ $KEYSTORE_DIR"
echo "  ✅ $PASSWORD_DIR"

echo ""
echo "--- Copying keystores and password files ---"
COPIED=0; SKIPPED=0
while IFS= read -r -d '' keyfile; do
    fname=$(basename "$keyfile")
    base="${fname%.json}"
    pass_src="$KEYS_DIR/${base}.txt"
    dest_key="$KEYSTORE_DIR/$fname"
    dest_pass="$PASSWORD_DIR/${base}.txt"

    if [ -f "$dest_key" ]; then
        echo "  [SKIP] $fname — already present"
        (( SKIPPED++ )) || true
        continue
    fi

    cp "$keyfile" "$dest_key"
    chmod 600 "$dest_key"

    if [ -f "$pass_src" ]; then
        cp "$pass_src" "$dest_pass"
        chmod 600 "$dest_pass"
    else
        echo "  ⚠️  No password file found for $fname — create $dest_pass manually"
    fi

    echo "  ✅ $fname"
    (( COPIED++ )) || true
done < <(find "$KEYS_DIR" -maxdepth 1 -name 'keystore-*.json' -print0)

echo ""
echo "  Copied: $COPIED  Skipped: $SKIPPED"
echo ""
echo "  ℹ️  Add to your Teku validator service flags:"
echo "     --validator-keys=${KEYSTORE_DIR}:${PASSWORD_DIR}"

if [ "$AUTO_RESTART" = "true" ] && [ -n "$SERVICE" ]; then
    echo ""
    echo "--- Restarting $SERVICE ---"
    sudo systemctl start "$SERVICE"
    sleep 3
    systemctl is-active --quiet "$SERVICE" \
        && echo "  ✅ Running" \
        || echo "  ❌ Failed — check: journalctl -u $SERVICE -n 30"
else
    echo ""
    echo "⚠️  Start manually: sudo systemctl start $SERVICE"
fi

echo ""
echo "$SEP"
echo "  Done. Verify on beaconcha.in after the next epoch."
echo "$SEP"
