#!/usr/bin/env bash
# =============================================================================
# import-validators-lodestar.sh — Import Obol DVT keystores into Lodestar VC.
#
# Designed for Ethereum on ARM / Obol DVT clusters.
# Keystores live in /home/ethereum/.charon/validator_keys/
#
# Each keystore-N.json has a matching keystore-N.txt with its own password,
# as generated by the Obol cluster creation process.
#
# Usage:
#   bash import-validators-lodestar.sh
#   bash import-validators-lodestar.sh \
#       --keys-dir  /home/ethereum/.charon/validator_keys \
#       --datadir   /home/ethereum/.lodestar-validator-obol
# =============================================================================
set -euo pipefail

KEYS_DIR="/home/ethereum/.charon/validator_keys"
DATADIR="/home/ethereum/.lodestar-validator-obol"
SERVICE=""
AUTO_RESTART=true

SEP="────────────────────────────────────────────"

usage() {
    cat << 'EOF'
Usage: bash import-validators-lodestar.sh [OPTIONS]

Options:
  --keys-dir  <path>  Keystore directory (default: ~/.charon/validator_keys)
  --datadir   <path>  Lodestar datadir   (default: ~/.lodestar-validator-obol)
  --service   <name>  Systemd service name (auto-detected if not set)
  --no-restart        Do not restart service after import
  --help              Show this help
EOF
    exit 0
}

while [ $# -gt 0 ]; do
    case "$1" in
        --keys-dir)  KEYS_DIR="$2";  shift 2 ;;
        --datadir)   DATADIR="$2";   shift 2 ;;
        --service)   SERVICE="$2";   shift 2 ;;
        --no-restart) AUTO_RESTART=false; shift ;;
        --help|-h)   usage ;;
        *) echo "Unknown option: $1"; usage ;;
    esac
done

[ ! -d "$KEYS_DIR" ] && { echo "ERROR: Keys dir not found: $KEYS_DIR"; exit 1; }

KEYSTORE_COUNT=$(find "$KEYS_DIR" -maxdepth 1 -name 'keystore-*.json' 2>/dev/null | wc -l)
[ "$KEYSTORE_COUNT" -eq 0 ] && { echo "ERROR: No keystores found in $KEYS_DIR"; exit 1; }

LODESTAR_BIN=""
for bin in /usr/local/bin/lodestar /usr/bin/lodestar; do
    [ -x "$bin" ] && { LODESTAR_BIN="$bin"; break; }
done

if [ -z "$SERVICE" ]; then
    for svc in lodestar-validator-obol-lido lodestar-validator-obol \
               lodestar-validator-lido lodestar-validator lodestar; do
        systemctl list-units --full --all 2>/dev/null | grep -q "${svc}.service" && \
            { SERVICE="$svc"; break; }
    done
    [ -z "$SERVICE" ] && AUTO_RESTART=false
fi

echo ""
echo "$SEP"
echo "  Lodestar Validator Key Import"
echo "$SEP"
echo "  Keys src  : $KEYS_DIR ($KEYSTORE_COUNT keystore(s))"
echo "  Datadir   : $DATADIR"
[ -n "$SERVICE" ] && echo "  Service   : $SERVICE"
echo "$SEP"
echo ""
echo "⚠️  SLASHING SAFETY — read before proceeding:"
echo "   1. Ensure the OLD validator is STOPPED."
echo "   2. Wait at least 2 epochs (~13 min) after stopping it."
echo "   3. NEVER run two validator instances with the same keys."
echo ""
read -rp "Type 'yes' to continue: " confirm
[ "$confirm" = "yes" ] || { echo "Aborted."; exit 0; }

if [ -n "$SERVICE" ] && systemctl is-active --quiet "$SERVICE" 2>/dev/null; then
    echo ""
    echo "--- Stopping $SERVICE ---"
    sudo systemctl stop "$SERVICE"
    echo "  ✅ Stopped"
    sleep 2
fi

echo ""
echo "--- Importing keystores ---"

if [ -n "$LODESTAR_BIN" ]; then
    # Lodestar validator import command — one keystore at a time
    # using per-keystore password files
    IMPORTED=0; FAILED=0
    while IFS= read -r -d '' keyfile; do
        fname=$(basename "$keyfile")
        base="${fname%.json}"
        pass_file="$KEYS_DIR/${base}.txt"

        if [ ! -f "$pass_file" ]; then
            echo "  [SKIP] $fname — no password file ${base}.txt"
            continue
        fi

        PASS=$(cat "$pass_file")
        PASS_TMP=$(mktemp)
        echo "$PASS" > "$PASS_TMP"

        "$LODESTAR_BIN" validator import \
            --dataDir "$DATADIR" \
            --keystore "$keyfile" \
            --password "$PASS_TMP" \
            --force 2>/dev/null && {
                echo "  ✅ $fname"
                (( IMPORTED++ )) || true
            } || {
                echo "  ❌ $fname — import failed"
                (( FAILED++ )) || true
            }
        rm -f "$PASS_TMP"
    done < <(find "$KEYS_DIR" -maxdepth 1 -name 'keystore-*.json' -print0)

    echo ""
    echo "  Imported: $IMPORTED  Failed: $FAILED"
else
    # Manual copy fallback
    echo "  lodestar binary not found — copying keystores manually."
    KEYSTORES_DIR="$DATADIR/keystores"
    SECRETS_DIR="$DATADIR/secrets"
    mkdir -p "$KEYSTORES_DIR" "$SECRETS_DIR"
    chmod 700 "$KEYSTORES_DIR" "$SECRETS_DIR"

    COPIED=0
    while IFS= read -r -d '' keyfile; do
        fname=$(basename "$keyfile")
        base="${fname%.json}"
        pass_file="$KEYS_DIR/${base}.txt"
        dest="$KEYSTORES_DIR/$fname"

        if [ -f "$dest" ]; then
            echo "  [SKIP] $fname"
            continue
        fi

        cp "$keyfile" "$dest"
        chmod 600 "$dest"

        [ -f "$pass_file" ] && {
            cp "$pass_file" "$SECRETS_DIR/${base}.txt"
            chmod 600 "$SECRETS_DIR/${base}.txt"
        }
        echo "  ✅ $fname"
        (( COPIED++ )) || true
    done < <(find "$KEYS_DIR" -maxdepth 1 -name 'keystore-*.json' -print0)
    echo "  Copied: $COPIED"
fi

if [ "$AUTO_RESTART" = "true" ] && [ -n "$SERVICE" ]; then
    echo ""
    echo "--- Restarting $SERVICE ---"
    sudo systemctl start "$SERVICE"
    sleep 3
    systemctl is-active --quiet "$SERVICE" \
        && echo "  ✅ Running" \
        || echo "  ❌ Failed — check: journalctl -u $SERVICE -n 30"
else
    echo ""
    echo "⚠️  Start manually: sudo systemctl start $SERVICE"
fi

echo ""
echo "$SEP"
echo "  Done. Verify on beaconcha.in after the next epoch."
echo "$SEP"
