# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Configuration Variables
  VM_MEMORY = "8192"
  VM_CPUS = 2
  NODE_VERSION = "20"
  NVM_VERSION = "v0.40.0"

  config.vm.box = "bento/ubuntu-24.04"
  config.vm.synced_folder ".", "/home/vagrant/ethereumonarm" # Sync current directory to /home/vagrant/ethereumonarm in the VM
  
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = VM_CPUS
    vb.memory = VM_MEMORY
  end

  config.vm.provision "shell", path: "provision.sh", env: {
    "NODE_VERSION" => NODE_VERSION,
    "NVM_VERSION" => NVM_VERSION
  }
end

