# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Configuration Variables
  VM_MEMORY = "8192"
  VM_CPUS = 2
  NODE_VERSION = "20"
  NVM_VERSION = "v0.40.0"

  config.vm.box = "bento/ubuntu-24.04"
  config.vm.synced_folder ".", "/home/vagrant/ethereumonarm" # Sync current directory to /home/vagrant/ethereumonarm in the VM
  
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = VM_CPUS
    vb.memory = VM_MEMORY
  end

  config.vm.provision "shell", path: "provision.sh", env: {
    "NODE_VERSION" => NODE_VERSION,
    "NVM_VERSION" => NVM_VERSION
  }

  config.vm.post_up_message = "
  ----------------------------------------------------------------------
    Welcome to the Ethereum on ARM Package Builder Environment!
  ----------------------------------------------------------------------

  This VM is running Ubuntu 24.04 and comes pre-configured with all the
  tools you need to build .deb packages for Ethereum clients on ARM.

  Included tools:
    - Docker & Docker Compose
    - Go, Rust, Node.js
    - FPM (Effing Package Management)
    - Cross-compilation toolchains

  To get started:
    1. Log in to the VM:
       vagrant ssh

    2. Navigate to the project directory:
       cd ethereumonarm

    3. Build all packages:
       make

  For more documentation, visit:
    https://ethereum-on-arm-documentation.readthedocs.io

  Join our community on Discord:
    https://discord.gg/ve2Z8fxz5N

  Happy building!
  ----------------------------------------------------------------------
  "
end

